### PR TITLE
code refactoring for benchmarking multiple algorithms

### PR DESCRIPTION
**Pull request by dariosalvi78**
main changes:

- "original" algorithm in its own module
- added algos folder where more algorithms will be added
- added a "dummy" algo that multiplies time by a constant step rate
- main.c simplified and decoupled from the espruino step counter
- fine tuning of thresholds for espruino step counter left in a separate main()

### CODE REVIEW

**Comment by gfwilliams** [comment]
Thanks - any chance of moving `const char *FILES[FILECOUNT] = {` and `EXPECTED_/etc` into a header file at minimum. so we can avoid the duplication?

It seems a shame that this ends up duplicating masses of code between `main.c` and `tuneEspruino.c`

**Comment by dariosalvi78** [comment]
yes, there is duplication, however I think that the two main()s serve two different purposes, one is for benchmarking different algos, the other is more specific to the current Espruino implementation, to fine tune its thresholds. It would be nice to have one single code for both but I am afraid that it would get too messy.

I could do some effort to place reused code in a separate file, so there's not too much duplication.

**Comment by gfwilliams** [comment]
I think where we've got the list of files used that would be good to avoid duplication - unless you're planning on completely redoing it, and the tuning should almost be a completely separate repo?

**Comment by dariosalvi78** [comment]
I will close this branch because we are working on a separate project which is more adapted to our needs. I'll report back when we've got something complete!

**Pull request closed without merging**
